spring:
  application:
    name: banka
  jpa:
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      # modify batch size as necessary
      hibernate:
        ddl-auto: update   # checks the DB schema and updates if necessary
    show-sql: true    # displaying sql scripts in console
    generate-ddl: true
  datasource:
#    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:postgresql://localhost:5410/bank
    username: postgres
    password: postgres

server:
  port: 8090   # exposing the port
  servlet:
    context-path: /api      # appends this to every API url
  error:
    include-message: always


jwt:
  secret: YNB7a8LvJosCYeBoYhvfaETcVTs7nWOY3IVWLvWC3Su3EGecc6lEb8kZgjQiG5vG
  # Token is valid 24 hours
  token.validity.seconds: 86400000

